### ISSUE TITLE
Menda theme, change the text links color on firefox history bookmarks suggestions

### ISSUE THREAD

**Issue by SMed79** [manjaro/artwork-menda#11]
Hello, 
i am using the default Manjaro 0.8.13 XFCE theme > Menda.
i want to change the text links color on firefox history/bookmarks suggestions.
i find **#0101E8** **#0909B2** **#15155F** very dark on a background **#1E1E1E** it is not easy to read !

![menda-0](https://cloud.githubusercontent.com/assets/1873139/8394847/660ead96-1d43-11e5-8683-0727cd1e8dbe.png)

![menda-1](https://cloud.githubusercontent.com/assets/1873139/8394848/6a8386ee-1d43-11e5-9071-66006e214f8c.png)

![menda-2](https://cloud.githubusercontent.com/assets/1873139/8394849/71dd10d6-1d43-11e5-9024-4001955196e1.png)

Thanks for help.
محمد

**Comment by korrode** [comment]
IIRC this needs to be addressed in the Firefox profile, not the GTK theme.
I thought the FF profile in our ISO profile did get modifications for this a while ago...

**Comment by SMed79** [comment]
Solved, thank you :) 
I did not have this stylesheet css file because i have previously restore my FF profile from an old backup.

![firefox-stylesheet](https://cloud.githubusercontent.com/assets/1873139/8401206/58d87216-1e23-11e5-970e-8a28f190965b.png)
