### ISSUE TITLE
Manjaro Warning: Icon Theme Has No Cache File

### ISSUE THREAD

**Issue by perknh** [manjaro/artwork-menda#14]
Manjaro Warning: this icon theme has no cache file.  You can create this by running gtk-update-icon-cache /usr/share/icons/Menda-Circle/ in a terminal emulator.  But, after doing so, there is this message:  "The generated cache was invalid."

**Comment by alexandruianu** [comment]
Cache files are irrelevant with vector graphics icons as far as I know, and Menda has svg (vector) icons.

**Comment by philmmanjaro** [comment]
19d251bce23ba64f30333dcddffb719bc813c504 fixes this
