### ISSUE TITLE
Warnings from Gnome applications (gt3)

### ISSUE THREAD

**Issue by lucasg** [manjaro/artwork-menda#16]
Several Gtk3 based application returns the following warnings:

Gtk-WARNING **: Theme parsing error: gtk-widgets.css:264:30: not a number
Gtk-WARNING **: Theme parsing error: mate-applications.css:37:23: 'none' is not a valid color name

The incriminating line for the first warning:
gtk-widgets.css:264 "text-shadow: 0 -1px ------------------+;"

Is that a typo ?

**Comment by philmmanjaro** [comment]
Maybe. Change it and if it works for you send in a patch.

**Comment by lucasg** [comment]
done.

**Comment by philmmanjaro** [comment]
Ok, fixed with todays release.
