### ISSUE TITLE
Firefox 43 using GTK3 introduces new issues

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/artwork-menda#19]
![firefox-43-gtk3](https://cloud.githubusercontent.com/assets/5050022/11824444/dda5a88e-a379-11e5-95d4-ec0a5dcdcc94.png)

Seems we have to add some quirks to GTK3 css to fix this.

**Comment by oberon2007** [comment]
No problem here after restarting firefox when I change the theme. Until that it looks like in your screenshot ;) But now:
![firefox](https://cloud.githubusercontent.com/assets/11800714/11825940/7cafda0a-a382-11e5-9bd6-1238eca4ded7.png)

**Comment by oberon2007** [comment]
Do you have the **/usr/share/themes/Menda-Dark/chrome** folder merged to **~/.mozilla/firefox/somename.default/** ?

**Comment by philmmanjaro** [comment]
I'm talking about the standard **Menda** theme, not dark. And I don't have that **chrome** thing enabled. I know that there is a theme, but somehow the new GTK3 messes it up.

**Comment by philmmanjaro** [comment]
Which version of **firefox** did you test?

**Comment by oberon2007** [comment]
Here's Menda: 
![fire_menda](https://cloud.githubusercontent.com/assets/11800714/11826379/698f5876-a385-11e5-8f75-6aec05e379cc.png)
**firefox 43.0-1**

**Comment by oberon2007** [comment]
Ah. ok. now I see it! :/

**Comment by oberon2007** [comment]
The inactive tabs are too dark.

**Comment by oberon2007** [comment]
Solved by merging the chrome-folder from **/usr/share/themes/Menda** to **~/.mozilla/firefox/somename.default/**

**Comment by oberon2007** [comment]
![firefox_bright](https://cloud.githubusercontent.com/assets/11800714/11826609/d15abeea-a386-11e5-95c8-53b97f4a9d0b.png)

**Comment by oberon2007** [comment]
Only problem is that it will not change back to dark theming until you copy the one from **/Menda-Dark** again ...

**Comment by philmmanjaro** [comment]
Well, what about the Menu? It is black in black. Same goes for the menus:
![ff43](https://cloud.githubusercontent.com/assets/5050022/11826853/1c82213c-a388-11e5-913b-fe9468b7f67d.png) Also the black one gets crazy if you longer navigate ...

**Comment by philmmanjaro** [comment]
Maybe some like this might help us also: https://github.com/horst3180/arc-firefox-theme/commit/897fc985c02801fcaae0e96267eb84ec009d43df

**Comment by philmmanjaro** [comment]
@oberon2007: seems my quirk made the menu visible but the green highlighting is gone. Arg ...

**Comment by oberon2007** [comment]
You mean the selected item in the menu? I think it would normally be defined by [selected_bg_color](https://github.com/manjaro/artwork-menda/blob/master/Menda/gtk-3.0/gtk-main-darker.css#L22) which is in this case [theme_selected_bg_color #8CBC65;](https://github.com/manjaro/artwork-menda/blob/master/Menda/gtk-3.0/gtk-main-darker.css#L5) but seems to be overridden by your fix ;)

**Comment by philmmanjaro** [comment]
@oberon2007: No the green highlighting isn't there also not in other themes like **vertex** (blue in that case). However for me it is more about the colour for the font.

**Comment by philmmanjaro** [comment]
However in the dark theme it is kinda fine, as there you can read the **menubar**. However I don't find that setting in the standard **menda** theme to fix. I'm not talking about the extra firefox theme. That is kinda fixed by now.

**Comment by korrode** [comment]
We have some customisations that related to Menda and Firefox here:
https://github.com/manjaro/manjaro-tools-iso-profiles/blob/master/shared/overlay/etc/skel/.mozilla/firefox/9shb6xj3.default/chrome/userChrome.css

It is perhaps that file that needs modifying.

**Comment by philmmanjaro** [comment]
@Kirek: no. I fixed it already in the Firefox chrome theme but using the default one there the menu-bar is black. Using the Menda Firefox chrome theme all is fine on my end. I might add it to the RC2 for now. What is still bugging me is the fact that it doesn't work without it. In the end using the Firefox theme makes the whole more complete.

**Comment by oberon2007** [comment]
My understanding after reading [Anex' instructions](https://github.com/manjaro/artwork-menda/blob/master/Menda/README-Firefox) was always that **userChrome.css** is not necessarily used at all. Only when you copy it into the profile.
In any case the **Greenbird** theme is one example I found that is still able to produce those highlights on the Firefox menubar also in absence of any userChrome.css ... and for that it uses the color defined in its **gtk-3.0/gtk.css**
gtk-theming is a pain! ;)

**Comment by philmmanjaro** [comment]
Jep. It is a pain. Maybe we should rebase **Menda** to a current theme. However I'm again stuck on the recolouring. Arc theme is nice, but it has a **cyan** touch. Maybe we can put more **magenta** into it.

![menda-2016](https://cloud.githubusercontent.com/assets/5050022/11840665/e0416820-a3f7-11e5-8e02-85fb6c7589c9.jpg)

**Comment by alexandruianu** [comment]
The new UserChrome.css isn't solving the text color in the inactive tabs.Looking into gtk3's css as oberon suggested might fix it.

**Comment by philmmanjaro** [comment]
@alexandruianu: post me some examples what is still wrong. You know I'm not a theme artist so I can't fix it.

**Comment by philmmanjaro** [comment]
@alexandruianu: I know that it is still broken if you don't apply the **chrome** theme for Firefox. But I don't know how to fix and for what I should look for ...

**Comment by jetm** [comment]
@philmmanjaro: After the upgrade of FF 43 with GTK3 I am using Greenbird theme (xfce-theme-greenbird package) and it works without Menda issues. Why not reuse that theme for Manjaro? It has green on it :)

**Comment by philmmanjaro** [comment]
Well, I found now a solution for the problem:

![firefox-43-menda-fixed](https://cloud.githubusercontent.com/assets/5050022/11858490/69565142-a462-11e5-8fb8-75798f2899ce.png)

**Comment by alexandruianu** [comment]
Good, is this why you didn't update menda along with menda-dark?

**Comment by philmmanjaro** [comment]
I updated this fix in both themes. Menda Dark has some other settings than the Menda and therefor other issues ...

**Comment by alexandruianu** [comment]
So what version is the updated theme? 20151216? Because with that I'm still getting dark text (chrome folder added to <whatever>.default or not). Repeated across 2 computers.

**Comment by philmmanjaro** [comment]
**20151217-1** is the latest.
