### ISSUE TITLE
huge black borders around gtk3 applications

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/artwork-menda#20]
This is also a really strange issue with Menda:

![gtk3-apps](https://cloud.githubusercontent.com/assets/5050022/11827768/0a35313e-a38f-11e5-92b1-e3d29010828a.png)

Huge black borders around gtk3 apps like **gedit**.

**Comment by oberon2007** [comment]
Try [THIS](https://github.com/manjaro/manjaro-tools-iso-profiles/blob/master/community/i3/i3-overlay/etc/skel/.config/gtk-3.0/gtk.css)

**Comment by philmmanjaro** [comment]
Seems it was a rendering issue on my end. Reverted the change as it all is fine.
