### ISSUE TITLE
Dashed border in dark theme bothers gnome terminal

### ISSUE THREAD

**Issue by apiraino** [manjaro/artwork-menda#6]
Hi,

I've installed your theme under Lubuntu (OpenBox 3.x).
I noticed an issue with gnome terminal caused by (after a long trial and error search) a dashed border in a css file.

I've fixed this behaviour changing a CSS:

```
diff --git a/Menda-Dark/gtk-3.0/gtk-widgets.css b/Menda-Dark/gtk-3.0/gtk-widgets.css
index ee77caa..00664ed 100755
--- a/Menda-Dark/gtk-3.0/gtk-widgets.css
+++ b/Menda-Dark/gtk-3.0/gtk-widgets.css
@@ -22,7 +22,8 @@
   -GtkDialog-action-area-border: 0;
   -GtkStatusbar-shadow-type: none;
   outline-color: alpha(@theme_fg_color, 0.3);
-  outline-style: dashed;
+  /* bug with gnome-terminal */
+  /* outline-style: dashed; */
   outline-offset: -3px;
   outline-width: 1px;
   outline-radius: 2px; }
```

Works for me, don't know it that dashed border for was there for a purpose.
Find attached two screenshots (before and after the fix).

btw, I love your theme.

cheers,
antonio

![ko](https://cloud.githubusercontent.com/assets/6098822/5994807/79098bca-aa82-11e4-885c-9a7586908fa7.png)
![ok](https://cloud.githubusercontent.com/assets/6098822/5994808/790e10f0-aa82-11e4-833a-09100080b743.png)

**Comment by vlaze** [comment]
You master! Saved my theme setup after hours of useless code reading. Happened to me with [http://opendesktop.org/content/show.php/White+%28El+Pacitan%29?content=173840](url). I don't know, though, the purpose of those 'hitboxes'... 

Thank you!

**Comment by oberon2007** [comment]
Just be aware that Menda themes are not compatible with gtk3.20 and will not be maintained further - sorry! Manjaro is now switching to [**vertex-maia-themes**](https://github.com/manjaro/packages-community/blob/master/vertex-maia-themes/PKGBUILD) which also includes a dark version - though, not as dark and not as green as Menda used to be :wink:

**Comment by vlaze** [comment]
Good to know. That green theme looks pretty neat! :smiley:
